-- ============================================================
--  CATÁLOGO exportado desde la base local
--  2026-09-22T14:30:57.295Z
--
--  Generado por worker/tools/exportar-catalogo.mjs — no editar a mano.
--  Contiene SOLO catálogo y configuración: ni pedidos, ni facturas,
--  ni cobros, ni usuarios, ni clientes.
--
--  Es idempotente: cada tabla se vacía antes de reinsertarse.
--  Cargar con:
--    npx wrangler d1 execute DB --remote --file=worker/tools/catalogo.sql
-- ============================================================

-- ─────────────── contacts (22 filas) ───────────────
DELETE FROM contacts WHERE id = 'consumidor-final' OR es_proveedor = 1;
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('consumidor-final', 'Consumidor final', 0, 1, NULL, NULL, 'Ficha para la venta de mostrador sin identificar. No la borres: la caja apunta aquí.', NULL, NULL, NULL, NULL, '222222222222', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-1', '10 fincas asociadas', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0001', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-10', 'Finca Alto Verde · Antioquia', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0010', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-11', 'Finca El Encanto · Antioquia', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0011', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-12', 'Finca El Manantial · Nariño', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0012', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-13', 'Finca El Mirador · Huila', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0013', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-14', 'Finca El Palmar · Tolima', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0014', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-15', 'Finca La Aurora · Boyacá', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0015', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-16', 'Finca La Esperanza · Cundinamarca', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0016', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-17', 'Finca Los Nogales · Antioquia', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0017', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-18', 'Finca Villa Clara · Huila', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0018', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-19', 'Huerto San Isidro · Boyacá', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0019', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-2', '3 fincas asociadas', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0002', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-20', 'Molino San Rafael · Boyacá', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0020', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-21', 'Vereda El Roble · Cundinamarca', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0021', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-3', 'Apiario Flor de Monte · Cauca', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0003', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-4', 'Asoc. Sumapaz · Cundinamarca', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0004', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-5', 'Asociación El Zulia · Santander', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0005', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-6', 'Cocina Agricultores · Bogotá', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0006', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-7', 'Colectivo Tierra Viva · Boyacá', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0007', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-8', 'Coop. del Valle · V. del Cauca', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0008', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO contacts (id, nombre, es_proveedor, es_cliente, telefono, direccion, notas, banco, tipo_cuenta, numero_cuenta, titular, documento, cupo_credito, dias_credito, activo, creado_en, actualizado_en) VALUES ('prov-9', 'Coop. La Sierra · S. Nevada', 1, 0, NULL, NULL, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.', NULL, NULL, NULL, NULL, 'NIT-0009', 0, 0, 1, '2026-09-04 13:43:53', '2026-09-04 13:43:53');

-- ─────────────── admin_groups (3 filas) ───────────────
DELETE FROM admin_groups;
INSERT INTO admin_groups (id, nombre, mostrar_filtro_fino, orden, activo, icono, creado_en, actualizado_en) VALUES ('frutas', 'Frutas', 0, 10, 1, 'fruta', '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO admin_groups (id, nombre, mostrar_filtro_fino, orden, activo, icono, creado_en, actualizado_en) VALUES ('verduras', 'Verduras', 0, 20, 1, 'hoja', '2026-09-04 13:43:53', '2026-09-04 13:43:53');
INSERT INTO admin_groups (id, nombre, mostrar_filtro_fino, orden, activo, icono, creado_en, actualizado_en) VALUES ('agroindustriales', 'Agroindustriales', 1, 30, 1, 'canasta', '2026-09-04 13:43:53', '2026-09-04 13:43:53');

-- ─────────────── categories (10 filas) ───────────────
DELETE FROM categories;
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('verduras', 'Verduras y raíces', 'Recolectadas al amanecer del domingo, en tu casa esa misma tarde.', 'agroindustriales', 'verduras', 10, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('frutas', 'Frutas frescas', 'Maduradas en el árbol, nunca en cámara.', 'agroindustriales', 'frutas', 20, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('lacteos', 'Leche de cabra', 'De un hato pequeño en el altiplano, ordeñado a mano.', 'agroindustriales', 'agroindustriales', 30, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('mieles', 'Mieles y apicultura', 'Miel, polen y propóleo de colmenares propios, sin pasteurizar.', 'agroindustriales', 'agroindustriales', 40, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('listos', 'Listos para comer', 'Preparados cada mañana con la cosecha del día.', 'agroindustriales', 'agroindustriales', 50, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('fermentos', 'Fermentos', 'Kambuchas y fermentados vivos, embotellados sin pasteurizar.', 'agroindustriales', 'agroindustriales', 60, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('panaderia', 'Panadería', 'Horneado el mismo día con harinas molidas en el altiplano.', 'agroindustriales', 'agroindustriales', 70, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('granos', 'Granos y semillas', 'Molidos en piedra y empacados en lotes pequeños.', 'agroindustriales', 'agroindustriales', 80, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('despensa', 'Despensa', 'Lo que sostiene la cocina durante todo el mes.', 'agroindustriales', 'agroindustriales', 90, 1, '', '2026-09-04 13:43:53');
INSERT INTO categories (id, nombre, descripcion, grupo_admin, grupo_admin_id, orden, activo, icono, actualizado_en) VALUES ('canastas', 'Canastas', 'La compra semanal resuelta en una sola caja.', 'agroindustriales', 'agroindustriales', 100, 1, '', '2026-09-04 13:43:53');

-- ─────────────── products (25 filas) ───────────────
DELETE FROM products;
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-01', 'tomate-chonto-en-rama', 'Tomate Chonto en Rama', 'Cortado con la rama para que aguante toda la semana', 'verduras', 'agroindustriales', 'verduras', 9800, 7600, NULL, 'kg', 1, 0, 'Finca La Aurora · Boyacá', 4.8, 214, 'bestseller', 0, 8, 15, 'C', 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&h=1125&q=80', 'Tres tomates rojos maduros unidos por su rama verde', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-02', 'tomate-de-huerta-grande', 'Tomate de Huerta Grande', 'Una sola pieza alcanza para toda la ensalada', 'verduras', 'agroindustriales', 'verduras', 11500, 9000, 13900, 'kg', 1, 0, 'Vereda El Roble · Cundinamarca', 4.6, 97, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&h=1125&q=80', 'Un tomate rojo brillante con su tallo, sobre un fondo verde desenfocado', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-03', 'papa-nativa-de-paramo', 'Papa Nativa de Páramo', 'Sembrada a 3.100 metros, de piel fina y sabor mantecoso', 'verduras', 'agroindustriales', 'verduras', 7200, 5600, NULL, 'kg', 1, 1, 'Asoc. Sumapaz · Cundinamarca', 4.7, 156, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Montón de papas de piel clara recién cosechadas', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-04', 'zanahoria-con-hoja', 'Zanahoria con Hoja', 'Se arranca joven, cuando todavía es dulce', 'verduras', 'agroindustriales', 'verduras', 8400, 6600, NULL, 'manojo', 1, 0, 'Finca El Manantial · Nariño', 4.9, 183, 'temporada', 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&h=1125&q=80', 'Manojos de zanahorias naranjas con sus hojas verdes en un puesto de mercado', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-05', 'aguacate-hass', 'Aguacate Hass', 'Te llega en su punto exacto, listo para abrir', 'verduras', 'agroindustriales', 'verduras', 4900, 1500, NULL, 'unidad', 1, 0, 'Finca Los Nogales · Antioquia', 4.8, 312, 'bestseller', 0, 21, 20, 'C', 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Mitad de aguacate con su hueso, sobre un fondo rosa liso', 1, NULL, NULL, NULL, '2026-09-22 14:27:43');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-06', 'raices-de-estacion', 'Raíces de Estación', 'Remolacha, nabo y zanahoria de colores, como salieron de la tierra', 'verduras', 'agroindustriales', 'verduras', 14600, 11400, NULL, 'canasta', 1, 0, 'Colectivo Tierra Viva · Boyacá', 4.5, 68, 'nuevo', 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'Remolachas, zanahorias, tomates y nabos de colores sobre un fondo negro', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-07', 'verduras-verdes-del-huerto', 'Verduras Verdes del Huerto', 'Brócoli, calabacín y habichuela recogidos el mismo día', 'verduras', 'agroindustriales', 'verduras', 16200, 12600, NULL, 'canasta', 1, 0, 'Finca El Encanto · Antioquia', 4.6, 121, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1557844352-761f2565b576?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'Canastas de mimbre con brócoli, calabacines y habichuelas en un puesto de mercado', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-08', 'manzana-roja-de-altura', 'Manzana Roja de Altura', 'El frío de la noche es lo que la vuelve crujiente', 'frutas', 'agroindustriales', 'frutas', 10300, 7700, NULL, 'kg', 1, 0, 'Huerto San Isidro · Boyacá', 4.6, 129, NULL, 0, 39, 12, 'C', 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Manzanas rojas apiladas, la del frente con gotas de agua', 1, NULL, NULL, NULL, '2026-09-04 13:44:00');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-09', 'fresa-de-temporada', 'Fresa de Temporada', 'De la mata a tu nevera en menos de doce horas', 'frutas', 'agroindustriales', 'frutas', 12900, 9700, 15500, 'libra', 1, 0, 'Finca La Esperanza · Cundinamarca', 4.9, 401, 'bestseller', 0, 14, 18, 'C', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=900&h=1125&q=80', 'Fresas rojas maduras muy juntas, vistas desde arriba', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-10', 'sandia-sin-semilla', 'Sandía Sin Semilla', 'Pesada, sonora y con el corazón rojo intenso', 'frutas', 'agroindustriales', 'frutas', 18000, 13500, NULL, 'unidad', 1, 0, 'Finca El Palmar · Tolima', 4.4, 74, 'temporada', 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'Sandía entera junto a una tajada que muestra su pulpa roja', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-11', 'mango-de-azucar', 'Mango de Azúcar', 'Pequeño, fibroso y absurdamente dulce', 'frutas', 'agroindustriales', 'frutas', 13400, 10000, NULL, 'kg', 1, 0, 'Finca Villa Clara · Huila', 4.8, 226, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'Mangos maduros de piel rosada y amarilla amontonados', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-12', 'banano-de-vereda', 'Banano de Vereda', 'Racimos pequeños, madurados sin cámara de gas', 'frutas', 'agroindustriales', 'frutas', 6800, 3740, NULL, 'kg', 1, 0, 'Asociación El Zulia · Santander', 4.5, 188, NULL, 0, 52, 12, 'C', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'Racimo de bananos amarillos sobre un fondo amarillo intenso', 1, NULL, NULL, NULL, '2026-09-04 13:44:00');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-13', 'citricos-y-tropicales', 'Cítricos y Tropicales', 'Papaya, cítricos, kiwi y aguacate en una sola caja', 'frutas', 'agroindustriales', 'frutas', 26900, 20200, NULL, 'canasta', 1, 0, 'Coop. del Valle · V. del Cauca', 4.7, 143, 'nuevo', 0, 39, 12, 'C', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'Mitades de papaya, naranjas, limas, kiwi y aguacate ordenadas sobre una superficie', 1, NULL, NULL, NULL, '2026-09-04 13:44:01');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-14', 'frutos-del-bosque', 'Frutos del Bosque', 'Arándano, cereza y mora recogidos a mano', 'frutas', 'agroindustriales', 'frutas', 22500, 16900, NULL, 'bolsa', 1, 0, 'Finca Alto Verde · Antioquia', 4.9, 96, NULL, 0, 0, 10, 'C', 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'Cuenco de coco con kiwi, fresas, cerezas y arándanos', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-15', 'ensalada-arcoiris', 'Ensalada Arcoíris', 'Ocho vegetales crudos, cortados esta mañana', 'listos', 'agroindustriales', 'agroindustriales', 16900, 9300, NULL, 'unidad', 1, 0, 'Cocina Agricultores · Bogotá', 4.7, 258, 'bestseller', 0, 39, 12, 'C', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Plato de ensalada con zanahoria rallada, rábano, lombarda y hojas verdes', 1, NULL, NULL, NULL, '2026-09-04 13:44:00');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-16', 'bowl-verde-con-aguacate', 'Bowl Verde con Aguacate', 'Aguacate, garbanzo, mango y brotes tiernos', 'listos', 'agroindustriales', 'agroindustriales', 19500, 10725, NULL, 'unidad', 1, 0, 'Cocina Agricultores · Bogotá', 4.8, 174, NULL, 0, 51, 12, 'C', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&h=1125&q=80', 'Bowl con aguacate, garbanzos, tomate, mango y brotes sobre hojas verdes', 1, NULL, NULL, NULL, '2026-09-04 13:44:01');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-17', 'bowl-andino-de-huevo', 'Bowl Andino de Huevo', 'Huevo campesino, rábano y tomate sobre quinua', 'listos', 'agroindustriales', 'agroindustriales', 18400, 10120, NULL, 'unidad', 1, 0, 'Cocina Agricultores · Bogotá', 4.6, 112, NULL, 0, 50, 12, 'C', 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Bowl con huevo cocido, tomate, pepino y rábano sobre una mesa de madera', 1, NULL, NULL, NULL, '2026-09-04 13:44:01');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-18', 'smoothie-de-fresa-y-chia', 'Smoothie de Fresa y Chía', 'Sin azúcar añadida: la fresa ya trae la suya', 'listos', 'agroindustriales', 'agroindustriales', 11200, 6200, NULL, 'unidad', 1, 0, 'Cocina Agricultores · Bogotá', 4.5, 89, 'nuevo', 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'Vaso de smoothie rosado con fresa, chía y menta, visto desde arriba', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-19', 'guiso-campesino-de-verduras', 'Guiso Campesino de Verduras', 'Cocción lenta de cuatro horas; tú solo lo calientas', 'listos', 'agroindustriales', 'agroindustriales', 21900, 12000, NULL, 'unidad', 1, 0, 'Cocina Agricultores · Bogotá', 4.7, 133, 'ultimas-unidades', 0, 4, 10, 'C', 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Olla de guiso de verduras humeante, espolvoreado con hierbas frescas', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-20', 'trigo-integral-molido-en-piedra', 'Trigo Integral Molido en Piedra', 'Sin refinar: conserva el germen y el salvado', 'granos', 'agroindustriales', 'agroindustriales', 9600, 6500, NULL, 'bolsa', 1, 0, 'Molino San Rafael · Boyacá', 4.6, 71, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Granos de trigo dorados llenando todo el encuadre', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-21', 'semillas-y-especias-selectas', 'Semillas y Especias Selectas', 'Doce variedades secadas al sol y molidas al pedido', 'granos', 'agroindustriales', 'agroindustriales', 24800, 16900, 29900, 'canasta', 1, 0, 'Coop. La Sierra · S. Nevada', 4.8, 104, NULL, 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&h=1125&q=80', 'Montoncitos de especias y semillas de colores ordenados sobre madera blanca', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-22', 'cafe-de-origen-tueste-medio', 'Café de Origen · Tueste Medio', 'Un solo lote, tostado la semana que lo pides', 'despensa', 'agroindustriales', 'agroindustriales', 32000, 17600, NULL, 'bolsa', 1, 0, 'Finca El Mirador · Huila', 4.9, 487, 'bestseller', 0, 127, 30, 'C', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Granos de café de tueste oscuro cubriendo toda la superficie', 1, NULL, NULL, NULL, '2026-09-04 13:44:01');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-23', 'miel-de-abeja-cruda', 'Miel de Abeja Cruda', 'Sin pasteurizar ni filtrar: cristaliza, y eso es buena señal', 'despensa', 'agroindustriales', 'agroindustriales', 28500, 17700, NULL, 'frasco', 1, 0, 'Apiario Flor de Monte · Cauca', 4.9, 265, 'temporada', 0, 42, 12, 'C', 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Cuchara de miel goteando dentro de un frasco de vidrio lleno', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-24', 'canasta-semanal-familiar', 'Canasta Semanal Familiar', 'Fruta y verdura para cuatro personas, sin repetir a la semana siguiente', 'canastas', 'agroindustriales', 'agroindustriales', 89000, 66800, 105000, 'canasta', 1, 0, '10 fincas asociadas', 4.8, 619, 'bestseller', 0, 25, 8, 'C', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'Frutas y verduras dispuestas en círculo alrededor de una tabla de madera', 1, NULL, NULL, NULL, '2026-09-04 13:43:53');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, grupo_admin_id, precio, precio_costo, precio_anterior, unidad, cantidad_unidad, vendido_por_peso, origen, rating, review_count, badge, destacado, stock_actual, stock_seguridad, categoria_abc, imagen, imagen_hover, imagen_alt, activo, parent_id, variante_etiqueta, codigo_barras, actualizado_en) VALUES ('p-25', 'canasta-del-mercado-grande', 'Canasta del Mercado · Grande', 'La compra completa del mes, en una sola entrega', 'canastas', 'agroindustriales', 'agroindustriales', 146000, 80300, NULL, 'canasta', 1, 0, '3 fincas asociadas', 4.7, 208, NULL, 0, 47, 12, 'C', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'Puesto de mercado rebosante de frutas y verduras de todos los colores', 1, NULL, NULL, NULL, '2026-09-04 13:44:01');

-- ─────────────── product_components (0 filas) ───────────────
DELETE FROM product_components;

-- ─────────────── product_wholesale_discounts (0 filas) ───────────────
DELETE FROM product_wholesale_discounts;

-- ─────────────── treasury_accounts (2 filas) ───────────────
DELETE FROM treasury_accounts;
INSERT INTO treasury_accounts (id, nombre, tipo, descripcion, saldo_inicial, activo, orden, creado_en) VALUES ('caja-efectivo', 'Caja (efectivo)', 'efectivo', 'El cajón del mostrador', 0, 1, 1, '2026-09-04 13:43:49');
INSERT INTO treasury_accounts (id, nombre, tipo, descripcion, saldo_inicial, activo, orden, creado_en) VALUES ('cuenta-bancaria', 'Cuenta bancaria', 'banco', 'Tarjeta y transferencias', 0, 1, 2, '2026-09-04 13:43:49');

-- ─────────────── app_settings (1 filas) ───────────────
DELETE FROM app_settings;
INSERT INTO app_settings (clave, valor, actualizado_en) VALUES ('pos_recibo_por_defecto', '1', '2026-09-04 13:43:49');
