-- ============================================================
--  GENERADO por worker/tools/generate-seed.mjs — no editar a mano.
--  Regenerar con:  npm run db:seed:build
--
--  Contraseña de todas las cuentas de demo: demo1234
--  Los hashes son PBKDF2-SHA256 y llevan su propio salt aleatorio,
--  por eso cambian en cada regeneración aunque la clave sea la misma.
-- ============================================================

DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM contacts;
DELETE FROM cash_closings;
DELETE FROM user_roles;
DELETE FROM users;
DELETE FROM products;

-- ─────────────────────────── Usuarios ───────────────────────────
INSERT INTO users (id, email, nombre, password_hash) VALUES ('u-01', 'inventario@agricultores.co', 'Sara Villamil', 'pbkdf2$100000$HeKIg1g2Q22aZABcD0CvzQ$yCmzQCI29t7H9WLyBfh5xTzSYLEytLrSsRTba5yJTAM');
INSERT INTO user_roles (user_id, role) VALUES ('u-01', 'ADMIN_INVENTARIO');
INSERT INTO users (id, email, nombre, password_hash) VALUES ('u-02', 'pedidos@agricultores.co', 'Diana Cardona', 'pbkdf2$100000$_yR4LGDOfOxz_bOJSjq1ug$K2glPpAFt1Rg3QV2M7MuuVVLs5Ox1NknSCnasMQ1nhI');
INSERT INTO user_roles (user_id, role) VALUES ('u-02', 'GESTOR_PEDIDOS');
INSERT INTO users (id, email, nombre, password_hash) VALUES ('u-03', 'admin@agricultores.co', 'Nicolás Ruiz', 'pbkdf2$100000$Fo-2lCAhHBgLt2ukfS4cmg$VEAMKfWKtDcajpT-CXpl4dVU-1Doii9CC2I0Xw_SXz8');
INSERT INTO user_roles (user_id, role) VALUES ('u-03', 'SUPER_ADMIN');

-- ─────────────────────────── Categorías ───────────────────────────
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('verduras', 'Verduras y raíces', 'Recolectadas al amanecer del domingo, en tu casa esa misma tarde.', 'verduras', 10);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('frutas', 'Frutas frescas', 'Maduradas en el árbol, nunca en cámara.', 'frutas', 20);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('lacteos', 'Leche de cabra', 'De un hato pequeño en el altiplano, ordeñado a mano.', 'agroindustriales', 30);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('mieles', 'Mieles y apicultura', 'Miel, polen y propóleo de colmenares propios, sin pasteurizar.', 'agroindustriales', 40);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('listos', 'Listos para comer', 'Preparados cada mañana con la cosecha del día.', 'agroindustriales', 50);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('fermentos', 'Fermentos', 'Kambuchas y fermentados vivos, embotellados sin pasteurizar.', 'agroindustriales', 60);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('panaderia', 'Panadería', 'Horneado el mismo día con harinas molidas en el altiplano.', 'agroindustriales', 70);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('granos', 'Granos y semillas', 'Molidos en piedra y empacados en lotes pequeños.', 'agroindustriales', 80);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('despensa', 'Despensa', 'Lo que sostiene la cocina durante todo el mes.', 'agroindustriales', 90);
INSERT INTO categories (id, nombre, descripcion, grupo_admin, orden) VALUES ('canastas', 'Canastas', 'La compra semanal resuelta en una sola caja.', 'agroindustriales', 100);

-- ─────────────────────────── Productos ───────────────────────────
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-01', 'tomate-chonto-en-rama', 'Tomate Chonto en Rama', 'Cortado con la rama para que aguante toda la semana', 'verduras', 'verduras', 9800, 7600, NULL, 'kg', 'Finca La Aurora · Boyacá', 4.8, 214, 'bestseller', 8, 15, 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&h=1125&q=80', 'Tres tomates rojos maduros unidos por su rama verde');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-02', 'tomate-de-huerta-grande', 'Tomate de Huerta Grande', 'Una sola pieza alcanza para toda la ensalada', 'verduras', 'verduras', 11500, 9000, 13900, 'kg', 'Vereda El Roble · Cundinamarca', 4.6, 97, NULL, 42, 12, 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&h=1125&q=80', 'Un tomate rojo brillante con su tallo, sobre un fondo verde desenfocado');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-03', 'papa-nativa-de-paramo', 'Papa Nativa de Páramo', 'Sembrada a 3.100 metros, de piel fina y sabor mantecoso', 'verduras', 'verduras', 7200, 5600, NULL, 'kg', 'Asoc. Sumapaz · Cundinamarca', 4.7, 156, NULL, 42, 12, 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Montón de papas de piel clara recién cosechadas');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-04', 'zanahoria-con-hoja', 'Zanahoria con Hoja', 'Se arranca joven, cuando todavía es dulce', 'verduras', 'verduras', 8400, 6600, NULL, 'manojo', 'Finca El Manantial · Nariño', 4.9, 183, 'temporada', 42, 12, 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&h=1125&q=80', 'Manojos de zanahorias naranjas con sus hojas verdes en un puesto de mercado');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-05', 'aguacate-hass', 'Aguacate Hass', 'Te llega en su punto exacto, listo para abrir', 'verduras', 'verduras', 4900, 3800, NULL, 'unidad', 'Finca Los Nogales · Antioquia', 4.8, 312, 'bestseller', 6, 20, 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Mitad de aguacate con su hueso, sobre un fondo rosa liso');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-06', 'raices-de-estacion', 'Raíces de Estación', 'Remolacha, nabo y zanahoria de colores, como salieron de la tierra', 'verduras', 'verduras', 14600, 11400, NULL, 'canasta', 'Colectivo Tierra Viva · Boyacá', 4.5, 68, 'nuevo', 42, 12, 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'Remolachas, zanahorias, tomates y nabos de colores sobre un fondo negro');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-07', 'verduras-verdes-del-huerto', 'Verduras Verdes del Huerto', 'Brócoli, calabacín y habichuela recogidos el mismo día', 'verduras', 'verduras', 16200, 12600, NULL, 'canasta', 'Finca El Encanto · Antioquia', 4.6, 121, NULL, 42, 12, 'https://images.unsplash.com/photo-1557844352-761f2565b576?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'Canastas de mimbre con brócoli, calabacines y habichuelas en un puesto de mercado');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-08', 'manzana-roja-de-altura', 'Manzana Roja de Altura', 'El frío de la noche es lo que la vuelve crujiente', 'frutas', 'frutas', 10300, 7700, NULL, 'kg', 'Huerto San Isidro · Boyacá', 4.6, 129, NULL, 42, 12, 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Manzanas rojas apiladas, la del frente con gotas de agua');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-09', 'fresa-de-temporada', 'Fresa de Temporada', 'De la mata a tu nevera en menos de doce horas', 'frutas', 'frutas', 12900, 9700, 15500, 'libra', 'Finca La Esperanza · Cundinamarca', 4.9, 401, 'bestseller', 14, 18, 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=900&h=1125&q=80', 'Fresas rojas maduras muy juntas, vistas desde arriba');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-10', 'sandia-sin-semilla', 'Sandía Sin Semilla', 'Pesada, sonora y con el corazón rojo intenso', 'frutas', 'frutas', 18000, 13500, NULL, 'unidad', 'Finca El Palmar · Tolima', 4.4, 74, 'temporada', 42, 12, 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'Sandía entera junto a una tajada que muestra su pulpa roja');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-11', 'mango-de-azucar', 'Mango de Azúcar', 'Pequeño, fibroso y absurdamente dulce', 'frutas', 'frutas', 13400, 10000, NULL, 'kg', 'Finca Villa Clara · Huila', 4.8, 226, NULL, 42, 12, 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'Mangos maduros de piel rosada y amarilla amontonados');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-12', 'banano-de-vereda', 'Banano de Vereda', 'Racimos pequeños, madurados sin cámara de gas', 'frutas', 'frutas', 6800, 5100, NULL, 'kg', 'Asociación El Zulia · Santander', 4.5, 188, NULL, 42, 12, 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'Racimo de bananos amarillos sobre un fondo amarillo intenso');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-13', 'citricos-y-tropicales', 'Cítricos y Tropicales', 'Papaya, cítricos, kiwi y aguacate en una sola caja', 'frutas', 'frutas', 26900, 20200, NULL, 'canasta', 'Coop. del Valle · V. del Cauca', 4.7, 143, 'nuevo', 42, 12, 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'Mitades de papaya, naranjas, limas, kiwi y aguacate ordenadas sobre una superficie');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-14', 'frutos-del-bosque', 'Frutos del Bosque', 'Arándano, cereza y mora recogidos a mano', 'frutas', 'frutas', 22500, 16900, NULL, 'bolsa', 'Finca Alto Verde · Antioquia', 4.9, 96, NULL, 0, 10, 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'Cuenco de coco con kiwi, fresas, cerezas y arándanos');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-15', 'ensalada-arcoiris', 'Ensalada Arcoíris', 'Ocho vegetales crudos, cortados esta mañana', 'listos', 'agroindustriales', 16900, 9300, NULL, 'unidad', 'Cocina Agricultores · Bogotá', 4.7, 258, 'bestseller', 42, 12, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Plato de ensalada con zanahoria rallada, rábano, lombarda y hojas verdes');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-16', 'bowl-verde-con-aguacate', 'Bowl Verde con Aguacate', 'Aguacate, garbanzo, mango y brotes tiernos', 'listos', 'agroindustriales', 19500, 10700, NULL, 'unidad', 'Cocina Agricultores · Bogotá', 4.8, 174, NULL, 42, 12, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&h=1125&q=80', 'Bowl con aguacate, garbanzos, tomate, mango y brotes sobre hojas verdes');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-17', 'bowl-andino-de-huevo', 'Bowl Andino de Huevo', 'Huevo campesino, rábano y tomate sobre quinua', 'listos', 'agroindustriales', 18400, 10100, NULL, 'unidad', 'Cocina Agricultores · Bogotá', 4.6, 112, NULL, 42, 12, 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&h=1125&q=80', 'Bowl con huevo cocido, tomate, pepino y rábano sobre una mesa de madera');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-18', 'smoothie-de-fresa-y-chia', 'Smoothie de Fresa y Chía', 'Sin azúcar añadida: la fresa ya trae la suya', 'listos', 'agroindustriales', 11200, 6200, NULL, 'unidad', 'Cocina Agricultores · Bogotá', 4.5, 89, 'nuevo', 42, 12, 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&h=1125&q=80', 'Vaso de smoothie rosado con fresa, chía y menta, visto desde arriba');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-19', 'guiso-campesino-de-verduras', 'Guiso Campesino de Verduras', 'Cocción lenta de cuatro horas; tú solo lo calientas', 'listos', 'agroindustriales', 21900, 12000, NULL, 'unidad', 'Cocina Agricultores · Bogotá', 4.7, 133, 'ultimas-unidades', 4, 10, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Olla de guiso de verduras humeante, espolvoreado con hierbas frescas');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-20', 'trigo-integral-molido-en-piedra', 'Trigo Integral Molido en Piedra', 'Sin refinar: conserva el germen y el salvado', 'granos', 'agroindustriales', 9600, 6500, NULL, 'bolsa', 'Molino San Rafael · Boyacá', 4.6, 71, NULL, 42, 12, 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Granos de trigo dorados llenando todo el encuadre');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-21', 'semillas-y-especias-selectas', 'Semillas y Especias Selectas', 'Doce variedades secadas al sol y molidas al pedido', 'granos', 'agroindustriales', 24800, 16900, 29900, 'canasta', 'Coop. La Sierra · S. Nevada', 4.8, 104, NULL, 42, 12, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&h=1125&q=80', 'Montoncitos de especias y semillas de colores ordenados sobre madera blanca');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-22', 'cafe-de-origen-tueste-medio', 'Café de Origen · Tueste Medio', 'Un solo lote, tostado la semana que lo pides', 'despensa', 'agroindustriales', 32000, 19800, NULL, 'bolsa', 'Finca El Mirador · Huila', 4.9, 487, 'bestseller', 120, 30, 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Granos de café de tueste oscuro cubriendo toda la superficie');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-23', 'miel-de-abeja-cruda', 'Miel de Abeja Cruda', 'Sin pasteurizar ni filtrar: cristaliza, y eso es buena señal', 'despensa', 'agroindustriales', 28500, 17700, NULL, 'frasco', 'Apiario Flor de Monte · Cauca', 4.9, 265, 'temporada', 42, 12, 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=900&h=1125&q=80', NULL, 'Cuchara de miel goteando dentro de un frasco de vidrio lleno');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-24', 'canasta-semanal-familiar', 'Canasta Semanal Familiar', 'Fruta y verdura para cuatro personas, sin repetir a la semana siguiente', 'canastas', 'agroindustriales', 89000, 66800, 105000, 'canasta', '10 fincas asociadas', 4.8, 619, 'bestseller', 25, 8, 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'Frutas y verduras dispuestas en círculo alrededor de una tabla de madera');
INSERT INTO products (id, slug, nombre, tagline, categoria_id, grupo_admin, precio, precio_costo, precio_anterior, unidad, origen, rating, review_count, badge, stock_actual, stock_seguridad, imagen, imagen_hover, imagen_alt) VALUES ('p-25', 'canasta-del-mercado-grande', 'Canasta del Mercado · Grande', 'La compra completa del mes, en una sola entrega', 'canastas', 'agroindustriales', 146000, 109500, NULL, 'canasta', '3 fincas asociadas', 4.7, 208, NULL, 42, 12, 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=900&h=1125&q=80', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=900&h=1125&q=80', 'Puesto de mercado rebosante de frutas y verduras de todos los colores');

-- ─────────────────────────── Contactos ───────────────────────────
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-1', '10 fincas asociadas', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-2', '3 fincas asociadas', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-3', 'Apiario Flor de Monte · Cauca', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-4', 'Asoc. Sumapaz · Cundinamarca', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-5', 'Asociación El Zulia · Santander', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-6', 'Cocina Agricultores · Bogotá', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-7', 'Colectivo Tierra Viva · Boyacá', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-8', 'Coop. del Valle · V. del Cauca', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-9', 'Coop. La Sierra · S. Nevada', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-10', 'Finca Alto Verde · Antioquia', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-11', 'Finca El Encanto · Antioquia', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-12', 'Finca El Manantial · Nariño', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-13', 'Finca El Mirador · Huila', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-14', 'Finca El Palmar · Tolima', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-15', 'Finca La Aurora · Boyacá', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-16', 'Finca La Esperanza · Cundinamarca', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-17', 'Finca Los Nogales · Antioquia', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-18', 'Finca Villa Clara · Huila', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-19', 'Huerto San Isidro · Boyacá', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-20', 'Molino San Rafael · Boyacá', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, es_proveedor, notas) VALUES ('prov-21', 'Vereda El Roble · Cundinamarca', 1, 'Creado desde el origen del catálogo. Completa teléfono y cuenta.');
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-1', 'Marcela Ospina', '300 214 5588', 'Calle 127 # 15-40, Bogotá', 1);
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-2', 'Julián Restrepo', '312 809 3321', 'Carrera 43A # 12-30, Medellín', 1);
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-3', 'Restaurante La Huerta', '601 745 2210', 'Carrera 9 # 68-30, Bogotá', 1);
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-4', 'Ana Lucía Peña', '318 662 7745', 'Avenida 6N # 23-18, Cali', 1);
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-5', 'Hotel Campestre El Roble', '310 455 9012', 'Km 3 vía Arcabuco, Villa de Leyva', 1);
INSERT INTO contacts (id, nombre, telefono, direccion, es_cliente) VALUES ('cli-6', 'Camilo Vargas', '317 990 4423', 'Calle 36 # 27-15, Bucaramanga', 1);

-- ─────────────────────────── Pedidos ───────────────────────────
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-01', 'ORD-1041', 'cli-1', 'Marcela Ospina', '300 214 5588', 'Calle 127 # 15-40, Bogotá', 'pendiente', 0, 153000, 0, 153000, NULL, NULL, '2026-08-09T08:14:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-01', 'p-24', 'Canasta Semanal Familiar', 89000, 66800, 1);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-01', 'p-22', 'Café de Origen · Tueste Medio', 32000, 19800, 2);
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-02', 'ORD-1042', 'cli-2', 'Julián Restrepo', '312 809 3321', 'Carrera 43A # 12-30, Medellín', 'pendiente', 0, 96000, 0, 96000, NULL, NULL, '2026-08-09T09:02:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-02', 'p-09', 'Fresa de Temporada', 12900, 9700, 3);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-02', 'p-23', 'Miel de Abeja Cruda', 28500, 17700, 1);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-02', 'p-03', 'Papa Nativa de Páramo', 7200, 5600, 4);
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-03', 'ORD-1043', 'cli-3', 'Restaurante La Huerta', '601 745 2210', 'Carrera 9 # 68-30, Bogotá', 'pendiente', 0, 107800, 0, 107800, NULL, NULL, '2026-08-09T10:35:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-03', 'p-05', 'Aguacate Hass', 4900, 3800, 12);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-03', 'p-01', 'Tomate Chonto en Rama', 9800, 7600, 5);
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-04', 'ORD-1039', 'cli-4', 'Ana Lucía Peña', '318 662 7745', 'Avenida 6N # 23-18, Cali', 'aprobado', 0, 53800, 0, 53800, 'u-02', '2026-08-08T17:05:00.000Z', '2026-08-08T16:20:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-04', 'p-13', 'Cítricos y Tropicales', 26900, 20200, 2);
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-05', 'ORD-1038', 'cli-5', 'Hotel Campestre El Roble', '310 455 9012', 'Km 3 vía Arcabuco, Villa de Leyva', 'enviado', 0, 203600, 0, 203600, 'u-02', '2026-08-08T12:30:00.000Z', '2026-08-08T11:48:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-05', 'p-25', 'Canasta del Mercado · Grande', 146000, 109500, 1);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-05', 'p-20', 'Trigo Integral Molido en Piedra', 9600, 6500, 6);
INSERT INTO orders (id, referencia, contact_id, cliente_nombre, cliente_telefono, cliente_direccion, estado, stock_reservado, subtotal, envio, total, aprobado_por, aprobado_en, creado_en) VALUES ('o-06', 'ORD-1044', 'cli-6', 'Camilo Vargas', '317 990 4423', 'Calle 36 # 27-15, Bucaramanga', 'pendiente', 0, 56200, 0, 56200, NULL, NULL, '2026-08-09T11:12:00.000Z');
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-06', 'p-15', 'Ensalada Arcoíris', 16900, 9300, 2);
INSERT INTO order_items (order_id, product_id, producto_nombre, precio_unitario, costo_unitario, cantidad) VALUES ('o-06', 'p-18', 'Smoothie de Fresa y Chía', 11200, 6200, 2);
